# Generated by Django 5.0.2 on 2024-03-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='客戶編號', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='姓名', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='電話', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='地址', max_length=255, null=True)),
                ('district', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='行政區', max_length=10, null=True)),
            ],
            options={
                'db_table': '客戶',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='商品編號', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='商品名稱', max_length=50, null=True)),
                ('price', models.FloatField(blank=True, db_column='單價', null=True)),
                ('stock', models.IntegerField(blank=True, db_column='庫存量', null=True)),
                ('discount', models.FloatField(blank=True, db_column='折扣', null=True)),
                ('image', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='圖片', max_length=100, null=True)),
            ],
            options={
                'db_table': '商品',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='門市編號', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='門市名稱', max_length=50, null=True)),
                ('tax_id', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='營業人統編', max_length=10, null=True)),
                ('address', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='地址', max_length=255, null=True)),
            ],
            options={
                'db_table': '門市',
            },
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.CharField(db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='訂單編號', max_length=10, primary_key=True, serialize=False)),
                ('gui_number', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='統一編號', max_length=20, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='日期', null=True)),
                ('random', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='隨機號', max_length=10, null=True)),
                ('serial', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CI_AS', db_column='序號', max_length=10, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='客戶編號', null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD.customer')),
                ('store', models.ForeignKey(blank=True, db_column='門市編號', null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD.store')),
            ],
            options={
                'db_table': '訂貨主檔',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, db_column='數量', null=True)),
                ('discount', models.FloatField(blank=True, db_column='折扣', null=True)),
                ('orderheader', models.OneToOneField(db_column='訂單編號', on_delete=django.db.models.deletion.PROTECT, to='CRUD.orderheader')),
                ('product', models.ForeignKey(db_column='商品編號', on_delete=django.db.models.deletion.CASCADE, to='CRUD.product')),
            ],
            options={
                'db_table': '訂貨明細',
                'unique_together': {('orderheader', 'product')},
            },
        ),
    ]
